name: Cypress Tests

on:
  pull_request:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        working-directory: ./web-app
        uses: cypress-io/github-action@v2

